### ISSUE TITLE
Missing styling options for indicators

### ISSUE THREAD

**Issue by shatanikmahanty** [apexlabs-ai/progress_builder#5]
Flutter allows styling through various properties of `LinearProgressIndicator`/ `CircularProgressIndicator`.

![image](https://user-images.githubusercontent.com/67138059/209426782-45f7e786-2019-4d1e-9025-cfbd186ed584.png)

Currently the package allows only limited customization of the progress bars through app wide theme override

Proposal to integrate these parameters into a class that allows users to configure the style using a style option object passed to the main `LinearProgressBuilder`/`CircularProgressBuilder` widget.

**Comment by adar2378** [comment]
I think this is not needed atm as users can use use `ProgressBuilder` directly use any customized widgets as the loading indicator. https://github.com/djangoflow/flutter_progress_builder/blob/master/lib/src/progress_builder.dart
